
default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5
  host: localhost
  username: rubyman
  password: '123'

development:
  <<: *default
  database: qna_development

test:
  <<: *default
  database: qna_test

